dist: xenial
sudo: required
language: python
python:
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install .

# command to run tests
script:
  - pytest --cov=odfuzz --cov-report html --cov-report term-missing

after_success:
  - codecov
  - pylint odfuzz tests
  - bandit -r -lll odfuzz tests

notifications:
    email:
        recipients:
            - petr.hanak@sap.com            
    on_success: always
    on_failure: always
