dist: trusty
language: python
python:
  - "3.6"

install:
  - pip install .
  - pip install -r requirements.txt

script:
  - pytest

deploy:
  provider: pypi
  user: test
  password: test
  server: http://pypi.brq.only.sap
  on:
    branch: master
