dist: xenial
sudo: required
language: python
python:
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install bandit

# command to run tests
script:
  - pytest
  - pylint odfuzz
  - make check
  - bandit -r -lll .

after_success:
  - codecov

notifications:
    email:
        recipients:
            - petr.hanak@sap.com            
    on_success: always
    on_failure: always
